# 根据需求添加相对应的role
- src: http://github.com/websoft9dev/role_common

- src: http://github.com/websoft9dev/role_cloud

- src: http://github.com/websoft9dev/role_apache

- src: http://github.com/websoft9dev/role_mysql

- src: http://github.com/websoft9dev/role_php-fpm

- src: http://github.com/websoft9dev/role_phpmyadmin

- src: http://github.com/websoft9dev/role_init_password

- src: http://github.com/websoft9dev/role_preend

- src: http://github.com/websoft9dev/role_end

- src: http://github.com/websoft9dev/role_9panel

- src: http://github.com/websoft9dev/role_lcmp

- src: http://github.com/websoft9dev/role_inotify_watch

- src: http://github.com/websoft9dev/role_redis
